[build]
  publish = "."
  command = "npm install"

[functions]
  directory = "netlify/functions"
  included_files = ["stati.csv"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
